name: LesRaisinsCore
version: '${project.version}'
main: me.xjqsh.lesraisinscore.LesRaisinsCore
api-version: 1.13
authors: [xjqsh]
description: Core plugins for LesRaisins mini games server.
commands:
  lesraisins:
    description: The main command of the plugin.